# Generated by Django 4.1.3 on 2022-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
